
version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: allowance-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: allowance_db
      MYSQL_USER: allowance_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "5506:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./allowback
    container_name: allowance-backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: kwucsani.iptime.org
      DB_PORT: 8944
      DB_USER: root
      DB_PASSWORD: 1001
      DB_NAME: allowance_db
    ports:
      - "3001:3001"

  frontend:
    build: ./allowfront
    container_name: allowance-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0

volumes:
  mysql-data:
