  backend:
    build: ./allowback
    container_name: allowance-backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: kwucsani.iptime.org
      DB_PORT: 8944
      DB_USER: root
      DB_PASSWORD: 1001
      DB_NAME: allowance_db
    ports:
      - "3001:3001"
